version: '3'

services:
  api:
    image: abdullah1308/go-redis-url-shortener:api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: abdullah1308/go-redis-url-shortener:db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
  client:
    image: abdullah1308/go-redis-url-shortener:client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api
      - db